### PR TITLE
first draft

### PR DESCRIPTION
**Pull request by cleberzavadniak**

### CODE REVIEW

**Comment by cleberzavadniak** [comment]
Ops! I found it is better to use `MessageAttributes` instead of using `topic` and `data` into the message body.
Changing that NOW.

**Comment by cleberzavadniak** [comment]
Yeap. Now you can review it. :)

**Comment by adolfosabino** [comment]
Teste falhou

**Comment by cleberzavadniak** [comment]
Falhou nada, seu mentiroso. Olha aí, passou de boas.

**Review by adolfosabino — APPROVED** [review]
:+1:

**Review by erickravaneli — APPROVED** [review]
:+1:

**Pull request merged**
